// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzclbI-CI-LQeXd1gY7z1s-BAJMedADKQ',
    appId: '1:788886031834:web:07312e760cbae080da84e3',
    messagingSenderId: '788886031834',
    projectId: 'smart-interview-coach-2b519',
    authDomain: 'smart-interview-coach-2b519.firebaseapp.com',
    storageBucket: 'smart-interview-coach-2b519.firebasestorage.app',
    measurementId: 'G-YC4KT9RX93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOZTeMXv9En9CVVJ1UW2aOLfKI-_0EZrU',
    appId: '1:788886031834:android:199db4128a0b3ba9da84e3',
    messagingSenderId: '788886031834',
    projectId: 'smart-interview-coach-2b519',
    storageBucket: 'smart-interview-coach-2b519.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzclbI-CI-LQeXd1gY7z1s-BAJMedADKQ',
    appId: '1:788886031834:web:19b643b62cee5acada84e3',
    messagingSenderId: '788886031834',
    projectId: 'smart-interview-coach-2b519',
    authDomain: 'smart-interview-coach-2b519.firebaseapp.com',
    storageBucket: 'smart-interview-coach-2b519.firebasestorage.app',
    measurementId: 'G-NSWY3XZ70K',
  );
}
